version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: match_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - match_bot_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_cache:
    image: redis:7-alpine
    container_name: match_redis_cache
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - match_bot_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi_bot:
    environment:
    - PROXY_URL=socks5://host.docker.internal:10808
    build:
      context: .
      dockerfile: Dockerfile
    container_name: match_fastapi_bot
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:8001:8000"

    depends_on:
      mysql_db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    networks:
      - match_bot_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  match_bot_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: